### ISSUE TITLE
Finding email addresses in arbitrary text

### ISSUE THREAD

**Issue by parshap** [jackbowman/email-addresses#16]
Hi!

Do you think this library can be used for finding emails in arbitrary texts? For example, I want to pull `parshap@gmail.com` out of the following string:

```
"My email address is parshap@gmail.com."
```

Right now I'm splitting the text on `/\s+/` and running each part though this module to see if it's an email address. Is there a better way to utilize this module?

Edit: Sometimes I have emails that are not separated by whitespace. For example `<strong>parshap@gmail.com</strong>` or `` `parshap@gmail.com` ``. Is there a more liberal (but still safe) boundary than `/\s+/`?

**Comment by jackbowman** [comment]
Hi!

You could use this library for that purpose, although it's not necessarily the best choice. It all depends on your goal. If you have arbitrary text, what percentage of emails do you want to pull out of it? If you have low expectations, just search for @ signs and see what's around them. If you have higher expectations, how fast do you need the emails out? The more time you have, the more different substrings you can try near the @ signs.

This library is intended for input that is supposed to be a well formed email address, and it's not optimized for performance. I'm guessing that doesn't fit with your use case.

**Comment by parshap** [comment]
Thanks for the input! I want to find 100% of emails within a text and performance isn't too important (this is offline analysis). I like the idea you're getting at: use a liberal search to find candidates and then use this library to make sure the email is real. Any thoughts on what characters around `@` I should include?  I.e., what characters can an email *not* begin or end with?

**Comment by jackbowman** [comment]
If you want to go by the spec, look at the "addr-spec" production, which in the common case boils down to a bunch of "atext"s followed by a "@" followed by a domain (a bunch of "dtext"s).

https://github.com/jackbowman/email-addresses/blob/master/lib/email-addresses.js#L367-377
https://github.com/jackbowman/email-addresses/blob/master/lib/email-addresses.js#L552-L613

Good luck!
