### ISSUE TITLE
Submit to JSDelivr

### ISSUE THREAD

**Issue by bradvogel** [jackbowman/email-addresses#20]
Mind submitting this to JSDelivr? https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

It allows us to fetch a bunch of libraries and concatenates them into a single request. Super useful!

**Comment by jackbowman** [comment]
Sure, why not: https://github.com/jsdelivr/jsdelivr/pull/11289

**Comment by bradvogel** [comment]
@jackbowman any chance you can submit a minified version?

**Comment by jackbowman** [comment]
https://github.com/jsdelivr/jsdelivr/pull/11369

**Comment by msimerson** [comment]
I think this issue wants to be closed and I'm sure this comment wants to be deleted.
