### ISSUE TITLE
dot at the and of the domain

### ISSUE THREAD

**Issue by derhuerst** [jackbowman/email-addresses#22]
[Test 35 indicates that `test@iana.org.` is not valid.](https://github.com/jackbowman/email-addresses/blob/f162304/test/tests.xml#L307) Can you please elaborate on this?

Edit: To make this clear – this is not meant as criticism. I don't understand why this is invalid if `iana.org.` is a valid domain.

**Comment by jackbowman** [comment]
@derhuerst Those particular tests are pulled from the is_email tests, which you can see more info on here: http://isemail.info/_system/is_email/test/?all .

TL;DR there's a lot of arcane rules.

**Comment by derhuerst** [comment]
So where shall I ask for more information? From what I can tell right now, this seems like a mistake.

**Comment by jackbowman** [comment]
@derhuerst I'm afraid that to my understanding this is correct "by the spec". RFC 5322 does not accept domains that end in a dot. See the link I posted http://isemail.info/_system/is_email/test/?all and mouse over the test. It shows the rules in the spec that define what the domain part of an email address is. Those rules don't allow for a dot at the end.

This is of course a contradiction with the full definition of a domain, which allows for a dot at the end. You are right that this seems odd. It's simply how it's been defined.

Keep in mind that this project is an implementation of "email addresses by the book". If you're looking to do something "in the real world" and you think that email addresses ending in dots are OK in your situation, use your own judgment.

**Comment by jackbowman** [comment]
@derhuerst If you are interested in the specs, you can look up the RFCs online. The relevant RFCs are mentioned in the source code of this project and in the isemail documentation.

**Comment by derhuerst** [comment]
@jackbowman I had [a similar situation before, where RFCs seemed to conflict with each other](https://github.com/jfhbrook/node-ecstatic/pull/156). I think in this case it's not crucial: Although I'm sure you can find a part of an RFC which mentions emails with trailing dot, emails almost never have the explicit dot in the end.

Thanks that you put a thought into this!
