### ISSUE TITLE
Support for rfc6854

### ISSUE THREAD

**Issue by baudehlo** [jackbowman/email-addresses#28]
rfc6854 allows a From address to be either a `mailbox-list` or an `address-list`.

The parser should support that.

It's a bit more complex than changing where to start the parser at, because if there's a "group" (or multiple groups) then the set of addresses should be collected under that group. For example: `Group1:foo@bar,boo@baz;, Group2:blah@fod;` should return 2 groups with the sets of addresses underneath them.

https://tools.ietf.org/html/rfc6854

**Comment by baudehlo** [comment]
Do you want me to submit a PR for this?

**Comment by jackbowman** [comment]
Makes sense to me! `parseFromAddress` or something like that? How will you handle the groups of addresses? I'm not going to do it myself so PR welcome.
